### ISSUE TITLE
Logo button

### ISSUE THREAD

**Issue by apdibbo** [stfc/cloud-openstack-horizon#7]
Clicking on the logo attempts to take you to /home/<WEBROOT>/<DEFAULT_DASHBOARD> which doesnt exist.
It should take you to /<WEBROOT>/<DEFAULT_DASHBOARD>

**Comment by l-mas** [comment]
changed the href="/"
but this redirects you to /projects/instances
is this fine?

**Comment by apdibbo** [comment]
That is perfect. 'project/instances' is the slug which is defined as being the default dashboard in local_settings
